baseURL = "http://tcp.cat"
languageCode = "en-us"
title = "TcpCat"
theme = "plain"

[[menu.main]]
name = "Home"
url = '/'
weight = "1"

[[menu.main]]
name = "about"
url = "/about"
weight = "2"


[params]
customCSS = ['style.css']
logo = ['logo.jpg']
