name: HugoToFirebase

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses:  actions/checkout@v2
        with:
          path: master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: setup Yarn
        uses: borales/actions-yarn@v2.0.0

      - name: new site
        run: |
          hugo new site $HOME/blog

      - name: copy file to blog dir
        run: |
          cd master
          rm -rf $HOME/blog/content/
          /bin/cp -rvf config.toml $HOME/blog/config.toml
          /bin/cp -rvf content/ $HOME/blog/content/
        
      - name: install theme
        run: |
          git clone https://github.com/yuuzao/plain.git $HOME/blog/themes/plain
                    
      - name: build
        run: |
          cd $HOME/blog
          HUGO_ENV=production hugo --gc --minify
           
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: public
        
      - name: commit changes
        run: |
            cd $HOME/blog/public
            git config --global user.email "w@tcp.cat"
            git config --global user.name "yuuzao"
            git init
            git remote add origin https://github.com/yuuzao/blog.git
            git status
            git branch
            git add .
            git commit -m "new post" -a

            git push origin https://yuuzao:${{ secrets.REPO_TOKEN }}@github.com/yuuzao/blog.git -f
            
