name: HugoToFirebase

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses:  actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: setup Yarn
        uses: borales/actions-yarn@v2.0.0

      - name: new site
        run: |
          hugo new site $HOME/blog


      - name: copy file to blog dir
        run: |
          rm -rf $HOME/blog/content/
          /bin/cp -rvf config.toml $HOME/blog/config.toml
          /bin/cp -rvf content/ $HOME/blog/content/
          /bin/cp -rvf firebase.json $HOME/blog/
        
      - name: install theme
        run: |
          git clone https://github.com/yuuzao/plain.git $HOME/blog/themes/plain
                    
      - name: build
        run: |
          cd $HOME/blog
          HUGO_ENV=production hugo --gc --minify
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SECRET_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.HOST }}

          
      - name: push to server
        run: |
            cd $HOME/blog
            rsync --delete -rvzh ./public/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/blog/
#           sudo curl -o "/usr/local/bin/firebase" -L https://firebase.tools/bin/linux/latest
#           sudo chmod +rx "/usr/local/bin/firebase"
#           cd $HOME/blog
#           firebase use khaki-161613 --token ${{ secrets.FIREBASE_TOKEN }}
#           firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
