name: HugoToFirebase

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses:  actions/checkout@v2
        with:
          path: master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: setup Yarn
        uses: borales/actions-yarn@v2.0.0

      - name: new site
        run: |
          hugo new site $HOME/blog

      - name: copy file to blog dir
        run: |
          cd master
          rm -rf $HOME/blog/content/
          /bin/cp -rvf config.toml $HOME/blog/config.toml
          /bin/cp -rvf content/ $HOME/blog/content/
        
      - name: install theme
        run: |
          git clone https://github.com/yuuzao/plain.git $HOME/blog/themes/plain
                    
      - name: build
        run: |
          cd $HOME/blog
          HUGO_ENV=production hugo --gc --minify
           
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: public
        
      - name: commit changes
        run: |
            echo "---"
            echo $(pwd)
            echo '----'
            mkdir -p public/public
            rm -rf public/public/*
            /bin/cp -rvf $HOME/blog/public/* public/public
            ls -a
            echo '--'
            cd public
            ls -a
            git status
            git checkout public
            echo '---'
            git config --local user.email "w@tcp.cat"
            git config --local user.name "yuuzao"
            git add . -f
            git commit -m "new post" -a
            git push origin public --force
            
            
